language: rust
sudo: false
matrix:
  include:
    - rust: 1.20.0
    - rust: stable
      env: STABLE=1
    - rust: nightly
      env: STABLE=1
branches:
  only:
    - master
script:
  - |
      cargo build -v &&
      cargo test -v --lib &&
      cargo test -v --doc &&
      cargo doc -v &&
      ([ "$STABLE" != 1 ] || cargo test )
